sonata_block:
  #context_manager: sonata.page.block.context_manager
  default_contexts: [sonata_page_bundle]

sonata_admin:
  assets:
    extra_javascripts:
      - bundles/applicationsonatapage/assets/js/app.js
      #- bundles/sonatapage/app.js
    extra_stylesheets:
      #- bundles/sonatapage/sonata-page.back.min.css
      - bundles/sonatapage/app.css

sonata_page:
  #is_inline_edition_on: false
  #slugify_service: sonata.page.slugify.cocur
  multisite: host_by_locale
  use_streamed_response: false
  hide_disabled_blocks: true

  router_auto_register:
    enabled: true
    priority: 150
  ignore_route_patterns:
    - ^(.*)admin(.*) # ignore admin route, ie route containing 'admin'
    - ^_(.*) # ignore symfony routes
    - ^homepage
    - ^_page
    - ^fos_user_(.*)
    - ^sonata_(.*)
    - ^hwi_(.*)
    - ^cms_(.*)
    - ^cron_(.*)
    - ^linkedin_(.*)
  ignore_routes:
    - sonata_page_cache_esi
    - sonata_page_cache_ssi
    - sonata_page_js_sync_cache
    - sonata_page_js_async_cache
    - sonata_cache_esi
    - sonata_cache_ssi
    - sonata_cache_js_async
    - sonata_cache_js_sync
    - sonata_cache_apc
    - cron_allow_withdrawl
  ignore_uri_patterns:
    - ^/admin\/ # ignore admin route, ie route containing 'admin'
  page_defaults:
    homepage: { decorate: false, enabled: true } # disable decoration for homepage, key - is a page route
  default_template: default
  templates:
    default:
      #path: '@SonataPage/layout.html.twig'
      path: "cms-templates/default.html.twig"
      name: "Inner Page"
      containers:
        content_top:
          name: Top content
          blocks:
            - sonata.cms.block.home_banner
        content:
          name: Main content
          blocks:
            - sonata.cms.block.services
      matrix:
        layout: |
          TTTTTTTT
          CCCCCCCC

        mapping:
          T: content_top
          C: content

    home:
      #path: '@SonataPage/layout.html.twig'
      path: "cms-templates/homepage.html.twig"
      name: "Home"
      containers:
        content_top:
          name: Top content
          blocks:
            - sonata.cms.block.home_banner

        content:
          name: Main content
          blocks:
            - sonata.cms.block.services
            - sonata.cms.block.brands
            - sonata.cms.block.faq
            - sonata.cms.block.awards
            - sonata.cms.block.testimonials
            - sonata.cms.block.blog
            - sonata.cms.block.our_work
      matrix:
        layout: |
          TTTTTTTT
          CCCCCCCC

        mapping:
          T: content_top
          C: content

  direct_publication: true #'%kernel.debug%'

  catch_exceptions:
    not_found: [404] # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
    fatal: [500] # so you can use the same page for different http errors or specify specific page for each error

  class:
    page: App\Application\Sonata\PageBundle\Entity\Page # This is an optional value
    snapshot: App\Application\Sonata\PageBundle\Entity\Snapshot
    block: App\Application\Sonata\PageBundle\Entity\Block
    site: App\Application\Sonata\PageBundle\Entity\Site
