parameters:
    #sonata.page.cms_manager.page.class: App\Application\Sonata\PageBundle\CmsManager\CmsPageManager

services:
#    sonata.page.cms.page:
#        public: true
#        class: '%sonata.page.cms_manager.page.class%'
#        tags:
#            - { name: sonata.page.manager, type: page }
#        arguments: ['@sonata.page.manager.page', '@sonata.page.block_interactor']
