
cms_page_by_locale:
    path: /{_site}/{path}
    defaults: { _controller: App\Application\Sonata\PageBundle\Controller\DefaultController::indexAction, , _site: us, path: "/" }
    requirements:
        _site:  us|ny
        path: "^(?!admin|login|_).+"

cms_page_slug:
    path: /{path}
    defaults: { _controller: App\Application\Sonata\PageBundle\Controller\DefaultController::indexAction, ,_site: us, path: "/" }
    requirements:
        _site:  us|ny
        #path: ".+"
        path: "^(?!admin|login|_).+"

