parameters:
  twig.controller.exception.class: App\Application\Sonata\PageBundle\Controller\ExceptionController

services:
  twig.controller.exception:
    class: "%twig.controller.exception.class%"
    arguments: ["@twig", "%kernel.debug%", "@service_container"]

  sonata.cms.block.home_banner:
    class: App\Application\Sonata\PageBundle\Block\Page\Home\HomeBannerBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.home_services:
    class: App\Application\Sonata\PageBundle\Block\Page\Home\HomeServicesBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.brands:
    class: App\Application\Sonata\PageBundle\Block\Page\Home\BrandsBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.faq:
    class: App\Application\Sonata\PageBundle\Block\Page\FAQBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.awards:
    class: App\Application\Sonata\PageBundle\Block\Page\Home\AwardsBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.testimonials:
    class: App\Application\Sonata\PageBundle\Block\Page\Home\TestimonialBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.blog:
    class: App\Application\Sonata\PageBundle\Block\Page\BlogBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.our_work:
    class: App\Application\Sonata\PageBundle\Block\Page\Home\OurWorkBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.banner_section:
    class: App\Application\Sonata\PageBundle\Block\Page\BannerBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.badges:
    class: App\Application\Sonata\PageBundle\Block\Page\BadgeBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.services:
    class: App\Application\Sonata\PageBundle\Block\Page\ServicesBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.portfolio:
    class: App\Application\Sonata\PageBundle\Block\Page\PortfolioBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.why_choose_us:
    class: App\Application\Sonata\PageBundle\Block\Page\WhyChooseUsBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.technology_stack:
    class: App\Application\Sonata\PageBundle\Block\Page\TechnologyStackBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.industries:
    class: App\Application\Sonata\PageBundle\Block\Page\IndustriesBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.processes:
    class: App\Application\Sonata\PageBundle\Block\Page\TheProcessBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.case_study_banner:
    class: App\Application\Sonata\PageBundle\Block\Page\CaseStudy\BannerBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.challenge_section:
    class: App\Application\Sonata\PageBundle\Block\Page\CaseStudy\ChallengeBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms.block.our_strategy_section:
    class: App\Application\Sonata\PageBundle\Block\Page\CaseStudy\OurStrategyBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]


  sonata.cms. block.our_approach_section:
    class: App\Application\Sonata\PageBundle\Block\Page\CaseStudy\OurApproachBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]

  sonata.cms. block.revenue_section:
    class: App\Application\Sonata\PageBundle\Block\Page\CaseStudy\RevenueBlockService
    tags:
      - { name: sonata.block }
    arguments:
      [ "@twig", "@service_container"]